version: "3"

services:

  coordinator:
    build:
      # Note the switch to the root project directory two levels up.
      # It allows the Dockerfile to assume that location as working dir.
      context: ../..
      dockerfile: coordinator/coordinator.dockerfile
    image: dev/styx-coordinator:latest
    ports:
      - "8886:8888"
    env_file:
    # Relative path of env file two levels up
      - ../../env/minio.env
    environment:
      - KAFKA_URL=kafka1:19092
      - HEARTBEAT_LIMIT=300000
      - HEARTBEAT_CHECK_INTERVAL=50000

  worker:
    build:
      # Note the switch to the root project directory two levels up.
      # It allows the Dockerfile to assume that location as working dir.
      context: ../..
      dockerfile: worker/worker.dockerfile
    image: dev/styx:latest
    environment:
      - WORKER_THREADS=${WORKER_THREADS}
      - INGRESS_TYPE=KAFKA
      - KAFKA_URL=kafka1:19092
      - DISCOVERY_HOST=coordinator
      - DISCOVERY_PORT=8888
    env_file:
    # Relative path of env file two levels up
      - ../../env/minio.env
    deploy:
      resources:
        limits:
          cpus: '${WORKER_THREADS}'
        reservations:
          cpus: '${WORKER_THREADS}'
